src/card/urls.py
from django.urls import path
from .views import *


app_name = "card"
urlpatterns = [
    path('card/add/<int:pk>/', BookInCardUpdateView.as_view(), name="add"),
    path('card/update/<int:pk>/', BookInCardUpdateView.as_view()),
    path('bookincard/delete/<int:pk>/', BookInCardDeleteView.as_view()),
    path('bookincard/<int:pk>/', BookInCardDetailView.as_view()),
    path('card/', CurrentCardListView.as_view(), name="list"),
    path('card/<int:pk>/', CardDetailView.as_view()),
    path('checkout/<int:pk>', OrderUpdateView.as_view(), name="order"),
    path('order/list/', OrderListView.as_view())
]

src/main/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic.base import RedirectView
from users.views import handler403, handler404
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('refers.urls')),
    path('', include('books.urls')),
    path('', include('users.urls')),
    path('', include('card.urls', namespace="card")),
    path('', include('search.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    re_path(r'^favicon\.ico$', RedirectView.as_view(url='/static/favicon.ico', permanent=True))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'users.views.handler404'
handler403 = 'users.views.handler403'

src/refers/models.py
from django.db import models
from datetime import datetime
from django_countries.fields import CountryField
# from django.contrib.contenttypes.fields import GenericRelation
# from search.models import Tag


class Genre(models.Model):
    name = models.CharField(
        unique=True,
        max_length=30,
        blank=False,
        null=False)
    created = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    def get_absolute_url(self):
        return f"/genre/{self.pk}/"
    def __str__(self):
        return self.name


class Publisher(models.Model):
    name = models.CharField(max_length=30, unique=True)
    email = models.EmailField(default='none@gmail.com', blank=True, null=True)
    created = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return f"/publisher/{self.pk}/"


class Series(models.Model):
    name = models.CharField(max_length=200, unique=True)
    created = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return f"/series/{self.pk}/"


class Author(models.Model):
    def year_birth():
        years = []
        for year in range(1700, datetime.now().year - 15):
            years.append((year, str(year)))
        return years

    def year_death():
        years = []
        for year in range(1700, datetime.now().year):
            years.append((year, str(year)))
        years.append(('', 'live'))
        return years

    name = models.CharField(
        max_length=30
    )
    surname = models.CharField(
        max_length=30
    )
    year_birth = models.SmallIntegerField(
        default=1990,
        choices=year_birth()
    )
    year_death = models.SmallIntegerField(
        default=datetime.now().year,
        choices=year_death(),
        null=True,
        blank=True)
    nationality = CountryField(
        null=True,
        blank=True
    )
    biography = models.CharField(
        max_length=500,
        null=True,
        blank=True
    )
    created = models.DateTimeField(
        auto_now=False,
        auto_now_add=True
    )
    updated = models.DateTimeField(
        auto_now=True,
        auto_now_add=False
    )
    # tags = GenericRelation(Tag)

    def get_absolute_url(self):
        return f"/author/{self.pk}/"

    def __str__(self):
        return self.name + '  ' + self.surname

src/templates/base.html
{% load static %}
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">

  <!-- main link --><link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
                    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css">
  <!-- own style --><link href="{% static 'starter-template.css' %}" rel="stylesheet">

    <title>{% block title %}{% endblock title %}</title>
    <!-- Custom styles for this template -->
    <link href="{% static 'starter-template.css' %}" rel="stylesheet">
    {% block style %}{% endblock style %}
  </head>

  <body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="/book/list/">
    <img src="{% static 'logo.jpg' %}" width="60" alt="">
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    {% include 'menu.html' %}
  <div style="width: 25%;">
      <form action="{% url 'search_results' %}" method="get" class="form-inline">
    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
  </div>
      {% if user.is_staff %}
    <div class="nav-item dropdown">
    <a class="nav-link dropdown-toggle"
       href="http://example.com"
       id="dropdown01"
       data-toggle="dropdown"
       aria-haspopup="true"
       aria-expanded="false">
      Опции для персонала
    </a>
    <div class="dropdown-menu" aria-labelledby="dropdown01">
      <a class="dropdown-item" href="/tags/">Управление тэгами</a>
    </div>
  </div>
    <div style="width: 50px;"></div>{% endif %}
      {% if user.is_authenticated %}
      <a href="/person/{{user}}/" class="btn btn-outline-success my-2 my-sm-0" role="button">{{user}}</a>
    <div style="width: 25px;"></div>{% endif %}
      <a href="{% url 'card:list' %}" class="btn btn-outline-success my-2 my-sm-0" role="button">Корзина</a>
    <div style="width: 25px;"></div>
      {% if user.is_authenticated %}
      <a href="/accounts/logout/" class="btn btn-outline-success my-2 my-sm-0" role="button">LOG OUT</a>
      {% else %}
      <a href="/accounts/login/" class="btn btn-outline-success my-2 my-sm-0" role="button">LOG IN</a>
      {% endif %}
  </div>
</nav>

<main role="main" class="container">
  {% block body %}
  {% endblock body %}
</main>

</body>
</html>

src/templates/menu.html
<ul class="navbar-nav mr-auto">
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle {% if current_menu == 'Авторы' %}active{% endif %}"
       href="http://example.com"
       id="dropdown01"
       data-toggle="dropdown"
       aria-haspopup="true"
       aria-expanded="false">Авторы
    </a>
    <div class="dropdown-menu" aria-labelledby="dropdown01">
      {% if user.is_authenticated %}<a class="dropdown-item" href="/author/list/">Просмотреть список</a>{% endif %}
      {% if perms.refers.add_author %}<a class="dropdown-item" href="/author/create/">Создать новый элемент</a>{% endif %}
    </div>
  </li>
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle {% if current_menu == 'Жанры' %}active{% endif %}"
       href="http://example.com"
       id="dropdown01"
       data-toggle="dropdown"
       aria-haspopup="true"
       aria-expanded="false">
      Жанры
    </a>
    <div class="dropdown-menu" aria-labelledby="dropdown01">
      {% if user.is_authenticated %}<a class="dropdown-item" href="/genre/list/">Просмотреть список</a>{% endif %}
      {% if perms.refers.add_genre %}<a class="dropdown-item" href="/genre/create/">Создать новый элемент</a>{% endif %}
    </div>
  </li>
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle {% if current_menu == 'Серии' %}active{% endif %}"
       href="http://example.com"
       id="dropdown01"
       data-toggle="dropdown"
       aria-haspopup="true"
       aria-expanded="false">
      Серии
    </a>
    <div class="dropdown-menu" aria-labelledby="dropdown01">
      {% if user.is_authenticated %}<a class="dropdown-item" href="/series/list/">Просмотреть список</a>{% endif %}
      {% if perms.refers.add_series %}<a class="dropdown-item" href="/series/create/">Создать новый элемент</a>{% endif %}
    </div>
  </li>
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle {% if current_menu == 'Издательства' %}active{% endif %}"
       href="http://example.com"
       id="dropdown01"
       data-toggle="dropdown"
       aria-haspopup="true"
       aria-expanded="false">
      Издательства
    </a>
    <div class="dropdown-menu" aria-labelledby="dropdown01">
      {% if user.is_authenticated %}<a class="dropdown-item" href="/publisher/list/">Просмотреть список</a>{% endif %}
      {% if perms.refers.add_publisher %}<a class="dropdown-item" href="/publisher/create/">Создать новый элемент</a>{% endif %}
    </div>
  </li>
</ul>