src/card/urls.py
from django.urls import path
from .views import *


app_name = "card"
urlpatterns = [
    path('card/add/<int:pk>/', BookInCardUpdateView.as_view(), name="add"),
    path('card/update/<int:pk>/', BookInCardUpdateView.as_view()),
    path('bookincard/delete/<int:pk>/', BookInCardDeleteView.as_view()),
    path('bookincard/<int:pk>/', BookInCardDetailView.as_view()),
    path('card/', CurrentCardListView.as_view(), name="list"),
    path('card/<int:pk>/', CardDetailView.as_view()),
    path('checkout/<int:pk>', OrderUpdateView.as_view(), name="order"),
    path('order/list/', OrderListView.as_view())
]

src/main/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic.base import RedirectView
from users.views import handler403, handler404
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('refers.urls')),
    path('', include('books.urls')),
    path('', include('users.urls')),
    path('', include('card.urls', namespace="card")),
    path('', include('search.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    re_path(r'^favicon\.ico$', RedirectView.as_view(url='/static/favicon.ico', permanent=True))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'users.views.handler404'
handler403 = 'users.views.handler403'

src/books/models.py
from django.db import models
from datetime import datetime
from refers.models import Genre, Publisher, Series, Author
from django.db.models.signals import pre_init
from django.dispatch import receiver


# Create your models here.
class Book(models.Model):
    def years_():
        years = []
        for year in range(1700, datetime.now().year + 3):
            years.append((year, str(year)))
        return years

    def pcs_():
        pcs = []
        for i in range(0, 101):
            pcs.append((i, str(i)))
        return pcs

    def rank_():
        rank = []
        for i in range(0, 11):
            rank.append((i, str(i)))
        return rank

    name = models.CharField(
        max_length=100
    )

    photo = models.ImageField(
        upload_to='books/static/',
        null=True,
        blank=True,
    )

    price = models.DecimalField(
        max_digits=6,
        decimal_places=2,
        default=1000.10
    )  # HTML with BYN

    author = models.ManyToManyField(
        Author,
        related_name='book',
        default=0
    )

    series = models.ForeignKey(
        Series,
        on_delete=models.CASCADE,
        related_name='book',
        null=True,
        blank=True
    )

    genre = models.ManyToManyField(
        Genre,
        related_name='book',
        default=0
    )

    year = models.IntegerField(
        choices=years_(),
        default=datetime.now().year,
        null=True,
        blank=True
    )

    pages = models.PositiveSmallIntegerField(
        default=10
    )

    cover = models.CharField(
        max_length=10,
        choices=[('hard', 'hardcover'),
                 ('soft', 'softcover')],
        default='softcover'
    )

    form = models.CharField(
        max_length=10,
        default='standard',
        choices=[
            ('pocket', '9x13 cm'),
            ('compact', '10.5x15.5 cm'),
            ('personal', '13x19.5 cm'),
            ('standard', '13.5x21.5 cm'),
            ('large', '17x24.4 cm'),
            ("reader's", '21.3x34.5 cm', )
        ]
    )

    ISBN = models.CharField(
        max_length=17,
        default='978-x-xx-xxxxxx-x'
    )  # HTML format 978-x-xx-xxxxxx-x

    weight = models.FloatField(
        default=0
    )  # HTML with "' ' g"

    age_limit = models.PositiveSmallIntegerField(
        default=0,
        choices=[
            (0, '0'),
            (6, '6'),
            (12, '12'),
            (16, '16'),
            (18, '18')]
    )  # HTML with "' '+"

    publisher = models.ForeignKey(
        Publisher,
        on_delete=models.CASCADE,
        related_name='book',
        null=True,
        blank=True
    )

    available_PCs = models.PositiveSmallIntegerField(
        default=1,
        choices=pcs_(),
        null=True,
        blank=True
    )  # HTML with 'PCs'

    available_bool = models.BooleanField(
        default=True
    )

    rank = models.PositiveSmallIntegerField(
        default=10,
        choices=rank_(),
        null=True,
        blank=True
    )

    created = models.DateTimeField(
        auto_now=False,
        auto_now_add=True
    )

    updated = models.DateTimeField(
        auto_now=True,
        auto_now_add=False
    )


    def __str__(self):
        return f'"{self.name}".  {self.list_author()}'

    def list_author(self):
        list_author = ''
        for author in self.author.all():
            list_author += author.name + ' ' + author.surname
        return list_author

    def get_absolute_url(self):
        return f"/book/{self.pk}/"

src/card/models.py
from django.db import models
from django.contrib.auth import get_user_model
from books.models import Book

User = get_user_model()

class Card(models.Model):
    user = models.ForeignKey(
        User,
        verbose_name="Клиент",
        related_name="cards",
        on_delete=models.PROTECT
    )

    def total_price(self):
        books = self.books.all()
        total = 0
        for book in books:
            total += book.price
        return total

class BookInCard(models.Model):
    book = models.ForeignKey(
        Book,
        verbose_name="Книга",
        related_name="books",
        on_delete=models.PROTECT
    )
    card = models.ForeignKey(
        Card,
        verbose_name="Корзина",
        related_name="books",
        on_delete=models.PROTECT
    )
    quantity = models.PositiveSmallIntegerField(
        verbose_name="Количество",
        default=1,
        null=False
    )
    price = models.DecimalField(
        max_digits=8,
        decimal_places=2
    )

    def price_for_one(self):
        price_for_one = self.price / self.quantity
        return price_for_one

    def __str__(self):
        return f"{self.book.name} * {self.quantity}"


class Order(models.Model):
    card = models.OneToOneField(
        Card,
        verbose_name="Корзина",
        related_name="order",
        on_delete=models.PROTECT
    )
    price = models.DecimalField(
        verbose_name="Стоимость заказа",
        max_digits=8,
        decimal_places=2
    )
    delivery_price = models.DecimalField(
        verbose_name="Цена доставки",
        max_digits=8,
        decimal_places=2
    )
    delivery_address = models.TextField(
        verbose_name="Адрес доставки",
    )
    status = models.CharField(
        max_length=20,
        default='в обработке',
        choices=[
            ('в обработке', 'в обработке'),
            ('передан курьеру', 'передан курьеру'),
            ('выполнен', 'выполнен'),
            ('отменен', 'отменен')
        ]
    )
    created = models.DateTimeField(
        auto_now=False,
        auto_now_add=True
    )
    updated = models.DateTimeField(
        auto_now=True,
        auto_now_add=False
    )

src/card/forms.py
from django.forms import ModelForm
from .models import BookInCard, Order
from books.models import Book
from django.forms.models import model_to_dict


class BookInCardForm(ModelForm):
    class Meta:
        model = BookInCard
        fields = ['quantity', ]
        labels = {'quantity': 'Укажите количество экземпляров, которое хотите заказать', }

    available_PCs = -1

    def __init__(self, instance=None, *args, **kwargs):
        data_from_book = model_to_dict(instance.book, 'available_PCs')
        self.available_PCs = data_from_book.get('available_PCs')
        super(BookInCardForm, self).__init__(instance=instance, *args, **kwargs)

    def clean(self, instance=None, *args, **kwargs):
        cleaned_data = super().clean()
        quantity = cleaned_data.get("quantity")
        if quantity > self.available_PCs:
            msg = "Такого количесва экземпляров выбранной книги нет в наличии"
            self.add_error('quantity', msg)

class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['delivery_address', ]

src/card/views.py
from django.views.generic.edit import UpdateView, DeleteView
from django.views.generic.list import ListView
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.core.mail import send_mail
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from .models import BookInCard, Card, Order
from books.models import Book
from .forms import *
from .utils import get_price
from random import choice


# BOOKINCARD
class BookInCardUpdateView(UpdateView):
    model = BookInCard
    form_class = BookInCardForm
    template_name = "create_card.html"
    success_url = reverse_lazy('card:list')

    def get_object(self):
        book_to_add = self.kwargs.get('pk')
        card_id = self.request.session.get('card_id')
        if not card_id:
            if self.request.user.is_anonymous:
                user = User.objects.get(pk=4)
            else:
                user = self.request.user
            card = Card.objects.create(user=user)
            self.request.session['card_id'] = card.pk
        else:
            card = Card.objects.get(pk=card_id)
        book = Book.objects.get(pk=book_to_add)
        book_in_card, created = BookInCard.objects.get_or_create(
            book=book,
            card=card,
            defaults={'price': book.price}
        )
        if not created:
            book_in_card.quantity = book_in_card.quantity + 1
            book_in_card.price = book.price * book_in_card.quantity
        return book_in_card

    def form_valid(self, form, **kwargs):
        quantity = form.cleaned_data.get('quantity')
        price = self.object.book.price
        total_price = quantity * price
        self.object.price = total_price
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class BookInCardDeleteView(DeleteView):
    model = BookInCard
    success_url = reverse_lazy('card:list')

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


class BookInCardDetailView(DetailView):
    model = BookInCard
    template_name = "detail_card.html"


# CARD
class CurrentCardListView(TemplateView):
    model = Card
    template_name = "list_current_card.html"
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        card_id = self.request.session.get('card_id')
        card = None
        if card_id:
            card = Card.objects.get(pk=card_id)

        # для предложения доп.книг пользователю
        if len(card.books.all()) > 0:
            genre_list = []
            for book in card.books.all():
                for genre in book.book.genre.all():
                    genre_list.append(genre)
            context['genre'] = choice(genre_list)
            author_list = []
            for book in card.books.all():
                for author in book.book.author.all():
                    author_list.append(author)
            context['author'] = choice(author_list)
        # ____________________________________

        context['card'] = card
        context['title'] = 'Корзина для заказа'
        context['action'] = 'Пожалуйста, проверьте Ваш заказ'
        context['url'] = '/card'
        context['delivery_price'] = get_price(card.total_price())[1]
        return context

class CardDetailView(DetailView):
    model = Card
    template_name = "list_card.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['title'] = 'Корзина для заказа'
        context['action'] = 'Пожалуйста, проверьте Ваш заказ'
        return context


# ORDER
class OrderUpdateView(UpdateView):
    model = Order
    form_class = OrderForm
    template_name = "order_create.html"
    success_url = '/book/list'

    def get_object(self):
        card_id = self.request.session.get('card_id')
        card = Card.objects.get(pk=card_id)
        user = card.user
        order, created = Order.objects.get_or_create(
            card=card,
            defaults={'price': get_price(card.total_price())[0],
                      'delivery_price': get_price(card.total_price())[1],
                      'delivery_address': user.person.location}
        )
        if created:
            self.request.session['order_id'] = order.pk
            order.price = get_price(card.total_price())[0]
            order.delivery_price = get_price(card.total_price())[1]
            order.delivery_address = user.person.location
            order.save()
        if not created:
            order.price = get_price(card.total_price())[0]
            order.delivery_price = get_price(card.total_price())[1]
            order.delivery_address = user.person.location
            order.save()
        return order

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action'] = 'Заполните необходимые поля для доставки'
        context['title'] = 'Оформление заказа'
        return context

    def get_success_url(self):
        order = Order.objects.get(pk=self.request.session.get('order_id'))
        for book in order.card.books.all():
            book.book.available_PCs = book.book.available_PCs - book.quantity
            book.book.save()
        self.request.session['order_id'] = None
        self.request.session['card_id'] = None
        if not self.request.user.is_anonymous:
            send_mail(
                'Подтверждение заказа',
                'Ваш заказ получен, укомплектован и будет отправлен',
                'genuine_fake@mail.ru',
                [self.request.user.email]
            )
        return super().get_success_url()

class OrderListView(ListView):
    model = Order
    template_name = 'order_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action'] = 'История заказов'
        context['title'] = 'Заказы'
        return context
    def get_queryset(self):
        if self.queryset is not None:
            queryset = self.queryset
            if isinstance(queryset, QuerySet):
                queryset = queryset.filter(card__user=self.request.user)
        elif self.model is not None:
            queryset = self.model._default_manager.filter(card__user=self.request.user)
        else:
            raise ImproperlyConfigured(
                "%(cls)s is missing a QuerySet. Define "
                "%(cls)s.model, %(cls)s.queryset, or override "
                "%(cls)s.get_queryset()." % {
                    'cls': self.__class__.__name__
                }
            )
        ordering = self.get_ordering()
        if ordering:
            if isinstance(ordering, str):
                ordering = (ordering,)
            queryset = queryset.order_by(*ordering)
        return queryset

src/card/templates/create_card.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block title %}
    Добавить в корзину
{% endblock title %}


{% block body %}
<div class="starter-template"><h1>Добавить в корзину</h1></div>
<div style="height: 50px;"></div>

<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <h3>Хотите добавить в корзину книгу
        <a href="/book/{{object.book.pk}}/">"{{object.book.name}}"</a>
        {% for author in object.book.author.all %}
            <a href="/author/{{author.pk}}/">
              {{ author.name }}
              {{ author.surname }}
            </a>{% endfor %}</h3>
    <table>
        {{ form|crispy }}
    </table>
    <h3>Доступно: {{object.book.available_PCs}} шт.</h3>

<div style="height: 50px;"></div>
<div style="height: 150px;">
    <button type="submit" class="btn btn-success btn-lg active">Сохранить</button>
    <a href="/book/list/" class="btn btn-primary btn-lg active" role="button" type="submit" aria-pressed="true">
        Вернуться к списку</a>
</form>
</div>

{% endblock body %}

src/card/templates/detail_card.html
{% extends 'base.html' %}
{% load custom_tags %}

{% block title %}
    Детали заказа
{% endblock title %}


{% block body %}
<div class="starter-template"><h1>Детали заказа</h1></div>
<h5>Уважаемый {{user}}, Вы планируете заказать книгу "{{object.book.name}}" в количестве {{object.quantity}} экз.</br>
    Общая цена, с учетом стоимости 1 экземпляра равной {{object.book.price}} BYN, составит {{object.price}} BYN = {{object.book.price}} BYN x {{object.quantity}} экз.
</h5>
<div style="padding: 25px 15px;">
    <p align="middle">
        <a href="/card" class="btn btn-primary btn-lg active"
           role="button" type="submit" aria-pressed="true">Просмотреть корзину</a>
    </p>
</div>
    <table class="table">
    <tr>
        <th>Индекс</th>
        <td>{{object.book.pk}}</td>
        <td rowspan="19" style = "border: 0px; padding: 0px 0px 0px 100px;">
            {% if object.book.photo != "" %}
            <img src="../../{{object.book.photo}}" height="600" widht="300">
            {% endif %}
        </td>
    </tr>
    <tr>
        <th>Название</th>
        <td>{{object.book.name}}</td>
    </tr>
    <tr>
        <th>Цена</th>
        <td>{{object.book.price}} BYN</td>
    </tr>
    <tr>
        <th>Автор(ы)</th>
        <td>
            {% for author in object.book.author.all %}
            <a href="/author/{{author.pk}}/">
                {{ author.name }}
                {{ author.surname }}<br>
            </a>
            {% endfor %}
        </td>
    </tr>
    <tr>
        <th>Серия</th>
        <td>
            <a href="/series/{{object.series.pk}}/">
                {{ object.book.series.name }}
            </a>
        </td>
    </tr>
    <tr>
        <th>Жанр(ы)</th>
        <td>
            {% for genre in object.book.genre.all %}
            <a href="/genre/{{genre.pk}}/">
                {{ genre.name }}<br>
            </a>
            {% endfor %}
        </td>
    </tr>
    <tr>
        <th>Год первоиздания</th>
        <td>{{object.book.year}}</td>
    </tr>
    <tr>
        <th>Кол-во страниц</th>
        <td>{{object.book.pages}}</td>
    </tr>
    <tr>
        <th>Тип обложки</th>
        <td>{{object.book.cover}}</td>
    </tr>
    <tr>
        <th>Формат издания</th>
        <td>{{object.book.form}}</td>
    </tr>
    <tr>
        <th>ISBN</th>
        <td>{{object.book.ISBN}}</td>
    </tr>
    <tr>
        <th>Вес</th>
        <td>{{object.book.weight}} г</td>
    </tr>
    <tr>
        <th>Возрастное ограничение</th>
        <td>{{object.book.age_limit}}+</td>
    </tr>
    <tr>
        <th>Издатель</th>
        <td>
            <a href="/publisher/{{object.book.publisher.pk}}/">
                {{object.book.publisher.name}}
            </a>
        </td>
    </tr>
    <tr>
        <th>Доступный остаток</th>
        <td>{{object.book.available_PCs}}, шт.</td>
    </tr>
    <tr>
        <th>Наличие</th>
        <td>{{object.book.available_bool}}</td>
    </tr>
    <tr>
        <th>Рейтинг</th>
        <td>{{object.book.rank}}/10</td>
    </tr>
</table>

<div style="padding: 40px 15px;">
    <p align="middle">
        <a href="/card" class="btn btn-primary btn-lg active"
           role="button" type="submit" aria-pressed="true">Просмотреть корзину</a>
    </p>
</div>
{% endblock body%}

src/card/templates/list_card.html
{% extends 'base.html' %}

{% block title %}
    {{title}}
{% endblock title %}


{% block body %}
<div class="album py-5 bg-light">
<div class="container">
  <div class="row">
    {% for book in object.books.all %}
    <div class="col-md-3">
      <div class="card mb-3 box-shadow">
        <div style="height: 155px;">
            <a href="/book/{{book.book.pk}}/">
            <img src="{{ book.book.photo.url }}" class="rounded mx-auto d-block" style="height: 155px; width: auto; align: center;" alt="Photo_cover">
            </a></div>
          <div class="card-body">
              <p class="card-text" style="text-align: center; height: 30px; vertical-align: middle"><a href="/book/{{book.book.pk}}/">{{book.book.name}}</a></p>
          <p class="card-text" style="text-align: center; height: 30px;">
            {% for author in book.book.author.all %}
            {% if user.is_authenticated %}<a href="/author/{{author.pk}}/">{% endif %}
              {{ author.name }}
              {{ author.surname }}
            </a>
            {% endfor %}
          </p>
          <p class="card-text" style="text-align: center; height: 30px; vertical-align: middle">{{book.price_for_one}} BYN за 1 экземпляр</p>
          <p class="card-text" style="text-align: center; height: 30px; vertical-align: middle">{{book.quantity}} экземпляр(ов) общей стоимостью {{book.price}} BYN</p>
        </div>
      </div>
    </div>
    {% endfor %}
     </div>
</div>
</div>
    <h3>Total price: {{object.total_price}} BYN</h3>
    <h3>Delivery price: {{object.order.delivery_price}} BYN</h3>
<div style="padding: 40px 15px;">
    <p align="middle">
        <a href="/order/list/" class="btn btn-primary btn-lg active"
           role="button" type="submit" aria-pressed="true">Вернуться к списку</a>
    </p>
</div>
{% endblock body %}

src/card/templates/list_current_card.html
{% extends 'base.html' %}
{% load custom_tags %}


{% block title %}
    {{title}}
{% endblock title %}


{% block body %}
<div class="starter-template"><h1>{{action}}</h1></div>

<table class="table">
  <thead class="thead-dark">
    <tr align="middle">
        <th scope="col">Наименование книги</th>
        <th scope="col">Количество экземпляров</th>
        <th scope="col">Цена за заказ, BYN</th>
        <th scope="col">Дополнительная информация</th>
        <th scope="col">Редактирование</th>
        <th scope="col">Удаление</th>
    </tr>
  </thead>
    {% for book in card.books.all %}
    <tr align="middle">
        <td><a href="/book/{{book.book.pk}}/">{{book.book}}</a></td>
        <td>{{book.quantity}}</td>
        <td>{{book.price}}</td>
        <td><a href="/bookincard/{{book.pk}}/"><i class="fas fa-info"></i></a></td>
        <td><a href="bookincard/update/{{book.book.pk}}/"><i class="far fa-edit"></i></a></td>
        <td><a href="/bookincard/delete/{{book.pk}}/"><i class="far fa-trash-alt"></i></a></td>
    </tr>
    {% endfor %}
</table>
    <h3 class="alert alert-success" role="alert">Стоимость книг: {{card.total_price}} BYN</h3>
    <h3 class="alert alert-success" role="alert">Стоимость доставки: {{delivery_price}} BYN</h3>
    <div style="height: 75px;"></div>
    <p align="center">
        <a href="/book/list" class="btn btn-primary btn-lg active"
            role="button" type="submit" aria-pressed="true">Добавить книгу к заказу</a>
    </p>
    <p align="center">
        <a href="{% url 'card:order' card.pk %}" class="btn btn-success btn-lg active"
            role="button" type="submit" aria-pressed="true">Оформить заказ</a>
    </p>

{% if card.books.all %}
<div style="height: 100px;"></div>
<h3 class="alert alert-primary" role="alert">Посмотрите еще книги из жанра {{genre}}</h3>
<div class="album py-5 bg-light">
<div class="container">
  <div class="row">
    {% for book in genre.book.all %}
    <div class="col-md-3">
      <div class="card mb-3 box-shadow">
        <div style="height: 155px;"><a href="/book/{{book.pk}}/">
          <img src="{{ book.photo.url }}" class="rounded mx-auto d-block" style="height: 155px; width: auto; align: center;" alt="Photo_cover"></a></div>
        <div class="card-body">
            <p class="card-text" style="text-align: center; height: 30px; vertical-align: middle"><a href="/book/{{book.pk}}/">{{book.name}}</a></p>
          <p class="card-text" style="text-align: center; height: 30px;">
            {% for author in book.author.all %}
            {% if user.is_authenticated %}<a href="/author/{{author.pk}}/">{% endif %}
              {{ author.name }}
              {{ author.surname }}
            </a>
            {% endfor %}
          </p>
          <p class="card-text" style="text-align: center; height: 30px; vertical-align: middle">{{book.price}} BYN</p>
          <div align="left">
              {% if user.is_authenticated %}<a href="/book/{{book.pk}}/"><i class="fas fa-info fa-1x" style="width: 75px;"></i></a>{% endif %}
              {% if book.available_bool == True and book.available_PCs > 0 %}<a href="{% url 'card:add' book.pk %}" type=""><i class="fas fa-cart-arrow-down fa-2x" style="width: 75px;"></i></a>
              {% else %}<i class="fas fa-ban fa-2x" style="width: 75px; color: gray;"></i>{% endif %}
              {% if perms.books.change_book %}<a href="/book/update/{{book.pk}}/"><i class="far fa-edit fa-1x"></i></a>{% endif %}
              {% if perms.books.delete_book %}<a href="/book/delete/{{book.pk}}/"><i class="far fa-trash-alt fa-1x"></i></a>{% endif %}
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
</div>
{% endif %}

{% if card.books.all %}
<div style="height: 100px;"></div>
<h3 class="alert alert-primary" role="alert">Посмотрите еще книги автора {{author.name}} {{author.surname}}</h3>
<div class="album py-5 bg-light">
<div class="container">
  <div class="row">
    {% for book in author.book.all %}
    <div class="col-md-3">
      <div class="card mb-3 box-shadow">
        <div style="height: 155px;"><a href="/book/{{book.pk}}/">
          <img src="{{ book.photo.url }}" class="rounded mx-auto d-block" style="height: 155px; width: auto; align: center;" alt="Photo_cover"></a></div>
        <div class="card-body">
            <p class="card-text" style="text-align: center; height: 30px; vertical-align: middle"><a href="/book/{{book.pk}}/">{{book.name}}</a></p>
          <p class="card-text" style="text-align: center; height: 30px;">
            {% for author in book.author.all %}
            {% if user.is_authenticated %}<a href="/author/{{author.pk}}/">{% endif %}
              {{ author.name }}
              {{ author.surname }}
            </a>
            {% endfor %}
          </p>
          <p class="card-text" style="text-align: center; height: 30px; vertical-align: middle">{{book.price}} BYN</p>
          <div align="left">
              {% if user.is_authenticated %}<a href="/book/{{book.pk}}/"><i class="fas fa-info fa-1x" style="width: 75px;"></i></a>{% endif %}
              {% if book.available_bool == True and book.available_PCs > 0 %}<a href="{% url 'card:add' book.pk %}" type=""><i class="fas fa-cart-arrow-down fa-2x" style="width: 75px;"></i></a>
              {% else %}<i class="fas fa-ban fa-2x" style="width: 75px; color: gray;"></i>{% endif %}
              {% if perms.books.change_book %}<a href="/book/update/{{book.pk}}/"><i class="far fa-edit fa-1x"></i></a>{% endif %}
              {% if perms.books.delete_book %}<a href="/book/delete/{{book.pk}}/"><i class="far fa-trash-alt fa-1x"></i></a>{% endif %}
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
</div>
{% endif %}
{% endblock body %}

src/card/templates/order_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block title %}
    {{title}}
{% endblock title %}


{% block body %}
<div class="starter-template"><h1>{{action}}</h1></div>
<div style="height: 50px;"></div>
<h3>Cтоимость заказа: {{ object.card.total_price }} BYN</h3>
<h3>Cтоимость доставки: {{ object.delivery_price }} BYN</h3>
<table class="table">
  <thead class="thead-dark">
    <tr align="middle">
        <th scope="col">Наименование книги</th>
        <th scope="col">Количество экземпляров</th>
        <th scope="col">Цена за заказ, BYN</th>
        <th scope="col">Дополнительная информация</th>
        <th scope="col">Редактирование</th>
        <th scope="col">Удаление</th>
    </tr>
  </thead>
    {% for book in object.card.books.all %}
    <tr align="middle">
        <td><a href="/book/{{book.book.pk}}/">{{book.book}}</a></td>
        <td>{{book.quantity}}</td>
        <td>{{book.price}}</td>
        <td><a href="/bookincard/{{book.pk}}/"><i class="fas fa-info"></i></a></td>
        <td><a href="/card/update/{{book.book.pk}}/"><i class="far fa-edit"></i></a></td>
        <td><a href="/bookincard/delete/{{book.pk}}/"><i class="far fa-trash-alt"></i></a></td>
    </tr>
    {% endfor %}
</table>
<div style="height: 50px;"></div>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{form|crispy}}
    </table>
<div style="height: 50px;"></div>
<div style="height: 150px;">
    <button type="submit" class="btn btn-success btn-lg active">Сохранить</button>
    <a href="{% url 'card:list' %}" class="btn btn-primary btn-lg active" role="button" type="submit" aria-pressed="true">
        Вернуться к корзине</a>
</div>
</form>
{% endblock body %}